all: Main.cpp Board.cpp GameStateManager.cpp Location.cpp Parser.cpp Player.cpp Screen.cpp
	g++ -g -std=c++11 Main.cpp Board.cpp GameStateManager.cpp Location.cpp Parser.cpp Player.cpp Screen.cpp -o memedemic
