all: Main.cpp Board.cpp Card.cpp GameStateManager.cpp Location.cpp Parser.cpp Player.cpp Screen.cpp
	g++ -g -std=c++17 Main.cpp Board.cpp Card.cpp GameStateManager.cpp Location.cpp Parser.cpp Player.cpp Screen.cpp -o memedemic
