#pragma once
#include <iostream>
#include <thread>
#include <chrono>
#include "GameStateManager.h"
#include "Screen.h"
#include "Location.h"

int testScript();

bool test0001(Board& board, GameStateManager& gsm, Parser& parser);
bool test0002(Board& board, GameStateManager& gsm, Parser& parser);
bool test0101(Board& board, GameStateManager& gsm, Parser& parser);
bool test0102(Board& board, GameStateManager& gsm, Parser& parser);
bool test0103(Board& board, GameStateManager& gsm, Parser& parser);
bool test0201(Board& board, GameStateManager& gsm, Parser& parser);
bool test0301(Board& board, GameStateManager& gsm, Parser& parser);
bool test0401(Board& board, GameStateManager& gsm, Parser& parser);
bool test0501(Board& board, GameStateManager& gsm, Parser& parser);
bool test0502(Board& board, GameStateManager& gsm, Parser& parser);
bool test0601(Board& board, GameStateManager& gsm, Parser& parser);
bool test0602(Board& board, GameStateManager& gsm, Parser& parser);
bool test0603(Board& board, GameStateManager& gsm, Parser& parser);
bool test0604(Board& board, GameStateManager& gsm, Parser& parser);
bool test0605(Board& board, GameStateManager& gsm, Parser& parser);
bool test0606(Board& board, GameStateManager& gsm, Parser& parser);
bool test0701(Board& board, GameStateManager& gsm, Parser& parser);
bool test0702(Board& board, GameStateManager& gsm, Parser& parser);
bool test0703(Board& board, GameStateManager& gsm, Parser& parser);
bool test0704(Board& board, GameStateManager& gsm, Parser& parser);
bool test0705(Board& board, GameStateManager& gsm, Parser& parser);
bool test0706(Board& board, GameStateManager& gsm, Parser& parser);
bool test0707(Board& board, GameStateManager& gsm, Parser& parser);
bool test0708(Board& board, GameStateManager& gsm, Parser& parser);
bool test0801(Board& board, GameStateManager& gsm, Parser& parser);
bool test0802(Board& board, GameStateManager& gsm, Parser& parser);
bool test0803(Board& board, GameStateManager& gsm, Parser& parser);
bool test0804(Board& board, GameStateManager& gsm, Parser& parser);
bool test0805(Board& board, GameStateManager& gsm, Parser& parser);
bool test0806(Board& board, GameStateManager& gsm, Parser& parser);
bool test0807(Board& board, GameStateManager& gsm, Parser& parser);
bool test0900(Board& board, GameStateManager& gsm, Parser& parser);
bool test0901(Board& board, GameStateManager& gsm, Parser& parser);
bool test0902(Board& board, GameStateManager& gsm, Parser& parser);
bool test1001(Board& board, GameStateManager& gsm, Parser& parser);
bool test1101(Board& board, GameStateManager& gsm, Parser& parser);
bool test1102(Board& board, GameStateManager& gsm, Parser& parser);
bool test1103(Board& board, GameStateManager& gsm, Parser& parser);
bool test1104(Board& board, GameStateManager& gsm, Parser& parser);
bool test1105(Board& board, GameStateManager& gsm, Parser& parser);
bool test1201(Board& board, GameStateManager& gsm, Parser& parser);
bool test1202(Board& board, GameStateManager& gsm, Parser& parser);
bool test1203(Board& board, GameStateManager& gsm, Parser& parser);
bool test1301(Board& board, GameStateManager& gsm, Parser& parser);
bool test1302(Board& board, GameStateManager& gsm, Parser& parser);
bool test1303(Board& board, GameStateManager& gsm, Parser& parser);
bool test1401(Board& board, GameStateManager& gsm, Parser& parser);
bool test1501(Board& board, GameStateManager& gsm, Parser& parser);
bool test1601(Board& board, GameStateManager& gsm, Parser& parser);
bool test1701(Board& board, GameStateManager& gsm, Parser& parser);
bool test1801(Board& board, GameStateManager& gsm, Parser& parser);
bool test1901(Board& board, GameStateManager& gsm, Parser& parser);
bool test2001(Board& board, GameStateManager& gsm, Parser& parser);
bool test2101(Board& board, GameStateManager& gsm, Parser& parser);
bool test2201(Board& board, GameStateManager& gsm, Parser& parser);
bool test2301(Board& board, GameStateManager& gsm, Parser& parser);
bool test2401(Board& board, GameStateManager& gsm, Parser& parser);
bool test2402(Board& board, GameStateManager& gsm, Parser& parser);
bool test2403(Board& board, GameStateManager& gsm, Parser& parser);
bool test2501(Board& board, GameStateManager& gsm, Parser& parser);
bool test2502(Board& board, GameStateManager& gsm, Parser& parser);
bool test2503(Board& board, GameStateManager& gsm, Parser& parser);
bool test2504(Board& board, GameStateManager& gsm, Parser& parser);
bool test2505(Board& board, GameStateManager& gsm, Parser& parser);
bool test2506(Board& board, GameStateManager& gsm, Parser& parser);
bool test2507(Board& board, GameStateManager& gsm, Parser& parser);
bool test2508(Board& board, GameStateManager& gsm, Parser& parser);
bool test2509(Board& board, GameStateManager& gsm, Parser& parser);
bool test2601(Board& board, GameStateManager& gsm, Parser& parser);
bool test2602(Board& board, GameStateManager& gsm, Parser& parser);
bool test2701(Board& board, GameStateManager& gsm, Parser& parser);
bool test2801(Board& board, GameStateManager& gsm, Parser& parser);
bool test2901(Board& board, GameStateManager& gsm, Parser& parser);
bool test3001(Board& board, GameStateManager& gsm, Parser& parser);
bool test3002(Board& board, GameStateManager& gsm, Parser& parser);
bool test3101(Board& board, GameStateManager& gsm, Parser& parser);
bool test3201(Board& board, GameStateManager& gsm, Parser& parser);
bool test3202(Board& board, GameStateManager& gsm, Parser& parser);
bool test3203(Board& board, GameStateManager& gsm, Parser& parser);
bool test3301(Board& board, GameStateManager& gsm, Parser& parser);
bool test3401(Board& board, GameStateManager& gsm, Parser& parser);
bool test3402(Board& board, GameStateManager& gsm, Parser& parser);
bool test3403(Board& board, GameStateManager& gsm, Parser& parser);
bool test3404(Board& board, GameStateManager& gsm, Parser& parser);
bool test3405(Board& board, GameStateManager& gsm, Parser& parser);
bool test3406(Board& board, GameStateManager& gsm, Parser& parser);
bool test3407(Board& board, GameStateManager& gsm, Parser& parser);
bool test3408(Board& board, GameStateManager& gsm, Parser& parser);
bool test3501(Board& board, GameStateManager& gsm, Parser& parser);
bool test3502(Board& board, GameStateManager& gsm, Parser& parser);
bool test3601(Board& board, GameStateManager& gsm, Parser& parser);